DYNAMO_ENDPOINT=http://localhost:8000
QUALTRICS_HOST=http://localhost:7001
QUALTRICS_API_KEY=some-api-key
USERS_TABLE=hrv-users
AWS_ACCESS_KEY_ID=accessKey
AWS_SECRET_ACCESS_KEY=secret
REGION=us-west-2
ONE_YR_CONSENT_SURVEY_ID=908abc